# camera_config.yaml
camera_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

camera_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "camera_joint"
  pid: {p: 1.0, i: 0.0, d: 0.0}


